/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */
export type FontCategory = "sans-serif" | "serif";
export interface FontDef { family: string; category: FontCategory; weights: number[] }
export const FONTS: FontDef[] = [
  {
    "family": "Outfit",
    "category": "sans-serif",
    "weights": [
      400,
      500,
      600
    ]
  },
  {
    "family": "Inter",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Roboto",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Open Sans",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Lato",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Montserrat",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Poppins",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Raleway",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Nunito",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Work Sans",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "DM Sans",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Manrope",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Space Grotesk",
    "category": "sans-serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Playfair Display",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Merriweather",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Lora",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "PT Serif",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Libre Baskerville",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Cormorant Garamond",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "EB Garamond",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Crimson Text",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Source Serif 4",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "DM Serif Display",
    "category": "serif",
    "weights": [
      400
    ]
  },
  {
    "family": "Fraunces",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  },
  {
    "family": "Spectral",
    "category": "serif",
    "weights": [
      400,
      700
    ]
  }
];
export const SANS_FONTS = FONTS.filter((f) => f.category === "sans-serif");
export const SERIF_FONTS = FONTS.filter((f) => f.category === "serif");
export const DEFAULT_FONT = "Inter";
/** CSS font-family value with a category fallback. */
export function fontStack(family: string): string {
  const def = FONTS.find((f) => f.family === family);
  return `"${family}", ${def?.category ?? "sans-serif"}`;
}
