import { defineConfig, devices } from "@playwright/test";
import { API_BASE_URL, API_PORT, OWNER_EMAIL, OWNER_NAME, OWNER_PASSWORD, OWNER_STORAGE_STATE, WEB_BASE_URL, WEB_PORT } from "./e2e/constants";

export default defineConfig({
  testDir: "./e2e",
  timeout: 60_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  // The whole suite drives one shared dev-mode API + SQLite database, so tests must not
  // interleave across files/workers: run everything on a single worker for determinism.
  workers: 1,
  retries: 0,
  reporter: [["list"]],
  globalSetup: "./e2e/global-setup.ts",
  use: {
    baseURL: WEB_BASE_URL,
    trace: "retain-on-failure",
    ...devices["Desktop Chrome"],
  },
  projects: [
    {
      name: "setup",
      testMatch: /auth\.setup\.ts/,
    },
    {
      name: "chromium",
      testMatch: /.*\.spec\.ts/,
      dependencies: ["setup"],
      use: { storageState: OWNER_STORAGE_STATE },
    },
  ],
  webServer: [
    {
      // CLIENT_URL must point at the e2e web server (5174), not the default 5173, or magic-link
      // and Google-callback redirects generated by the API land on the unrelated dev server.
      // PUBLIC_BASE_URL is pinned to the API's own origin so the Twilio webhook URL (and the
      // signature computed against it) is deterministic regardless of CLIENT_URL -- inbound.spec.ts
      // signs requests against `${API_BASE_URL}/api/inbound/twilio` and needs the server to agree.
      command: `PORT=${API_PORT} DATA_DIR=./data/e2e CLIENT_URL=${WEB_BASE_URL} PUBLIC_BASE_URL=${API_BASE_URL} ADMIN_EMAIL=${OWNER_EMAIL} ADMIN_PASSWORD=${OWNER_PASSWORD} ADMIN_NAME=${OWNER_NAME} npx tsx server/src/index.ts`,
      url: `${API_BASE_URL}/api/health`,
      reuseExistingServer: false,
      timeout: 60_000,
    },
    {
      command: `VITE_API_PROXY=${API_BASE_URL} npm run dev -w client -- --port ${WEB_PORT} --strictPort`,
      url: WEB_BASE_URL,
      reuseExistingServer: false,
      timeout: 60_000,
    },
  ],
});
