/**
 * Downloads a curated set of Google Fonts (latin subset, 400 + 700 weights) into
 * client/public/fonts and generates client/src/fonts.css + client/src/lib/fontManifest.ts.
 * Run: node scripts/fetch-fonts.mjs
 * Fonts are served from the app itself — no CDN at runtime.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const outDir = path.join(root, "client/public/fonts");
const cssOut = path.join(root, "client/src/fonts.css");
const manifestOut = path.join(root, "client/src/lib/fontManifest.ts");

const FONTS = [
  // Sans-serif
  { family: "Outfit", category: "sans-serif", weights: [400, 500, 600] },
  { family: "Inter", category: "sans-serif" },
  { family: "Roboto", category: "sans-serif" },
  { family: "Open Sans", category: "sans-serif" },
  { family: "Lato", category: "sans-serif" },
  { family: "Montserrat", category: "sans-serif" },
  { family: "Poppins", category: "sans-serif" },
  { family: "Raleway", category: "sans-serif" },
  { family: "Nunito", category: "sans-serif" },
  { family: "Work Sans", category: "sans-serif" },
  { family: "DM Sans", category: "sans-serif" },
  { family: "Manrope", category: "sans-serif" },
  { family: "Space Grotesk", category: "sans-serif" },
  // Serif
  { family: "Playfair Display", category: "serif" },
  { family: "Merriweather", category: "serif" },
  { family: "Lora", category: "serif" },
  { family: "PT Serif", category: "serif" },
  { family: "Libre Baskerville", category: "serif" },
  { family: "Cormorant Garamond", category: "serif" },
  { family: "EB Garamond", category: "serif" },
  { family: "Crimson Text", category: "serif" },
  { family: "Source Serif 4", category: "serif" },
  { family: "DM Serif Display", category: "serif", weights: [400] },
  { family: "Fraunces", category: "serif" },
  { family: "Spectral", category: "serif" },
];

// A modern Chrome UA makes Google return woff2 with unicode-range subsets.
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36";
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");

async function fetchCss(family, weights) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, "+")}:wght@${weights.join(";")}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${family}: css ${res.status}`);
  return res.text();
}

/** Parse @font-face blocks, keep the latin subset per weight. */
function parseFaces(css) {
  const faces = [];
  const blocks = css.split("@font-face").slice(1);
  for (const block of blocks) {
    const comment = /\/\*\s*([a-z0-9-]+)\s*\*\//i.exec(block)?.[1] ?? "";
    const weight = Number(/font-weight:\s*(\d+)/.exec(block)?.[1] ?? 400);
    const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    if (!url) continue;
    faces.push({ subset: comment, weight, url, unicodeRange });
  }
  // prefer the "latin" subset; fall back to the first face for each weight
  const byWeight = new Map();
  for (const f of faces) {
    const cur = byWeight.get(f.weight);
    if (!cur || (f.subset === "latin" && cur.subset !== "latin")) byWeight.set(f.weight, f);
  }
  return [...byWeight.values()];
}

await fs.mkdir(outDir, { recursive: true });
const css = [];
const manifest = [];
for (const font of FONTS) {
  const weights = font.weights ?? [400, 700];
  const faces = parseFaces(await fetchCss(font.family, weights));
  const files = [];
  for (const face of faces) {
    const file = `${slug(font.family)}-${face.weight}.woff2`;
    const res = await fetch(face.url, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`${font.family} ${face.weight}: font ${res.status}`);
    await fs.writeFile(path.join(outDir, file), Buffer.from(await res.arrayBuffer()));
    files.push({ weight: face.weight, file });
    css.push(`@font-face {\n  font-family: "${font.family}";\n  font-style: normal;\n  font-weight: ${face.weight};\n  font-display: swap;\n  src: url("/fonts/${file}") format("woff2");\n}`);
  }
  manifest.push({ family: font.family, category: font.category, weights: files.map((f) => f.weight) });
  console.log(`✓ ${font.family} (${files.map((f) => f.weight).join(", ")})`);
}

await fs.writeFile(cssOut, `/* Generated by scripts/fetch-fonts.mjs — self-hosted Google Fonts, no CDN. */\n${css.join("\n")}\n`);
await fs.writeFile(
  manifestOut,
  `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */
export type FontCategory = "sans-serif" | "serif";
export interface FontDef { family: string; category: FontCategory; weights: number[] }
export const FONTS: FontDef[] = ${JSON.stringify(manifest, null, 2)};
export const SANS_FONTS = FONTS.filter((f) => f.category === "sans-serif");
export const SERIF_FONTS = FONTS.filter((f) => f.category === "serif");
export const DEFAULT_FONT = "Inter";
/** CSS font-family value with a category fallback. */
export function fontStack(family: string): string {
  const def = FONTS.find((f) => f.family === family);
  return \`"\${family}", \${def?.category ?? "sans-serif"}\`;
}
`,
);
console.log(`Wrote ${manifest.length} fonts to ${path.relative(root, outDir)}`);
